In [2]:
pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.4.2-cp37-cp37m-win_amd64.whl (7.1 MB)
Requirement already satisfied: numpy>=1.16 in c:\users\laksh\anaconda3\envs\rstudio\lib\site-packages (from matplotlib) (1.20.3)
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\laksh\anaconda3\envs\rstudio\lib\site-packages (from matplotlib) (2.4.7)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\laksh\anaconda3\envs\rstudio\lib\site-packages (from matplotlib) (2.8.1)
Collecting pillow>=6.2.0
  Downloading Pillow-8.2.0-cp37-cp37m-win_amd64.whl (2.2 MB)Note: you may need to restart the kernel to use updated packages.

Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.3.1-cp37-cp37m-win_amd64.whl (51 kB)
Requirement already satisfied: six in c:\users\laksh\anaconda3\envs\rstudio\lib\site-packages (from cycler>=0.10->matplotlib) (1.15.0)
Installing collected packages: cycler, pillow, kiwisolver, matplotlib
Successfully installed cycler-0.10.0 kiwisolver-1.3.1 matplotlib-3.4.2 pillow-8.2.0

In [4]:
pip install pdfcrowd

Collecting pdfcrowd
  Downloading pdfcrowd-5.1.3-py2.py3-none-any.whl (39 kB)
Installing collected packages: pdfcrowd
Successfully installed pdfcrowd-5.1.3
Note: you may need to restart the kernel to use updated packages.

In [6]:
pip install ipynb

Collecting ipynb
  Using cached ipynb-0.5.1-py3-none-any.whl (6.9 kB)
Installing collected packages: ipynb
Successfully installed ipynb-0.5.1
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd
import os
import numpy as np
from itertools import combinations
from matplotlib import pyplot as plt
import pdfcrowd
from ipynb.fs.full.BSE_Scraping import security_names

# identify the top 10 gainers (%) across groups over the 5 years period. 
# Note: The gain is the closing price on the last day of the period, divided by the closing price on the first day of the period, minus 1.

In [5]:
data = {}
for root,dirs,files in os.walk(os.curdir):
    for file in files:
        if file.endswith('.csv') and file.startswith("5"):
            name = os.path.splitext(file)[0]
            df = pd.read_csv(file,thousands=",")
            df["Date"] = pd.to_datetime(df["Date"])
            df.sort_values(by="Date",inplace=True)
            
            try :
                start = df["Close"].iloc[0]
            except Exception as e:
                start = df["Close Price"].iloc[0]
            
            try :
                end = df["Close"].iloc[-1]
            except Exception as e:
                end = df["Close Price"].iloc[-1]
            gain = (end/start) - 1
            data[name] = gain

In [6]:
df = pd.DataFrame(data.items(),columns=["security","gain"])
df.sort_values(by="gain",inplace=True,ascending=False)
df.head(10)

    security      gain
273   524634  9.699531
94    504132  7.057637
130   511539  5.025157
25    500052  4.462151
163   514183  4.285132
132   511549  3.658902
95    504176  3.190584
259   523610  3.184641
198   517569  3.103940
79    500800  3.062201

# identify the top 10 gainers (%) across groups over the 3 years period.

In [7]:
data = {}
for root,dirs,files in os.walk(os.curdir):
    for file in files:
        if file.endswith('.csv') and file.startswith("5"):
            name = os.path.splitext(file)[0]
            df = pd.read_csv(file,thousands=",")
            df = df[0:750]
            df["Date"] = pd.to_datetime(df["Date"])
            df.sort_values(by="Date",inplace=True)
            
            try :
                start = df["Close"].iloc[0]
            except Exception as e:
                start = df["Close Price"].iloc[0]
            
            try :
                end = df["Close"].iloc[-1]
            except Exception as e:
                end = df["Close Price"].iloc[-1]
            gain = (end/start) - 1
            data[name] = gain

In [8]:
df = pd.DataFrame(data.items(),columns=["security","gain"])
df.sort_values(by="gain",inplace=True,ascending=False)
df.head(10)

    security      gain
130   511539  5.025157
132   511549  3.658902
293   526638  2.924000
136   511571  2.624595
104   504340  2.522727
16    500034  2.037351
163   514183  1.955581
229   521222  1.869128
253   523566  1.679487
142   511601  1.545455


# identify the top 10 gainers (%) across groups over the 2 years period.

In [9]:
data = {}
for root,dirs,files in os.walk(os.curdir):
    for file in files:
        if file.endswith('.csv') and file.startswith("5"):
            name = os.path.splitext(file)[0]
            df = pd.read_csv(file,thousands=",")
            df = df[0:500]
            df["Date"] = pd.to_datetime(df["Date"])
            df.sort_values(by="Date",inplace=True)
            
            try :
                start = df["Close"].iloc[0]
            except Exception as e:
                start = df["Close Price"].iloc[0]
            
            try :
                end = df["Close"].iloc[-1]
            except Exception as e:
                end = df["Close Price"].iloc[-1]
            gain = (end/start) - 1
            data[name] = gain

In [10]:
df = pd.DataFrame(data.items(),columns=["security","gain"])
df.sort_values(by="gain",inplace=True,ascending=False)
df.head(10)

    security      gain
130   511539  5.025157
280   524663  3.147255
293   526638  2.924000
229   521222  1.869128
163   514183  1.799353
79    500800  1.717421
27    500058  1.417910
68    500304  1.364921
136   511571  1.309278
177   517429  1.262162

# identify the top 10 gainers (%) across groups over the 1 year period.

In [11]:
data = {}
for root,dirs,files in os.walk(os.curdir):
    for file in files:
        if file.endswith('.csv') and file.startswith("5"):
            name = os.path.splitext(file)[0]
            df = pd.read_csv(file,thousands=",")
            df = df[0:250]
            df["Date"] = pd.to_datetime(df["Date"])
            df.sort_values(by="Date",inplace=True)
            
            try :
                start = df["Close"].iloc[0]
            except Exception as e:
                start = df["Close Price"].iloc[0]
            
            try :
                end = df["Close"].iloc[-1]
            except Exception as e:
                end = df["Close Price"].iloc[-1]
            gain = (end/start) - 1
            data[name] = gain

In [12]:
df = pd.DataFrame(data.items(),columns=["security","gain"])
df.sort_values(by="gain",inplace=True,ascending=False)
df.head(10)

    security      gain
104   504340  7.611111
183   517467  5.974138
280   524663  5.541995
130   511539  5.025157
162   514175  3.939286
96    504180  3.626728
98    504220  3.159091
293   526638  2.924000
27    500058  2.375000
229   521222  2.166667

# identify the top 10 gainers (%) across groups over the 6 months period.

In [13]:
data = {}
for root,dirs,files in os.walk(os.curdir):
    for file in files:
        if file.endswith('.csv') and file.startswith("5"):
            name = os.path.splitext(file)[0]
            df = pd.read_csv(file,thousands=",")
            df = df[0:130]
            df["Date"] = pd.to_datetime(df["Date"])
            df.sort_values(by="Date",inplace=True)
            
            try :
                start = df["Close"].iloc[0]
            except Exception as e:
                start = df["Close Price"].iloc[0]
            
            try :
                end = df["Close"].iloc[-1]
            except Exception as e:
                end = df["Close Price"].iloc[-1]
            gain = (end/start) - 1
            data[name] = gain

In [14]:
df = pd.DataFrame(data.items(),columns=["security","gain"])
df.sort_values(by="gain",inplace=True,ascending=False)
df.head(10)

    security      gain
104   504340  6.045455
252   523558  4.932692
279   524661  3.440000
248   523519  3.287356
327   535657  2.963636
293   526638  2.924000
274   524640  2.794643
280   524663  2.665441
119   511451  2.473333
176   517421  2.412628

# identify the top 10 gainers (%) across groups over the 3 months period.

In [15]:
data = {}
for root,dirs,files in os.walk(os.curdir):
    for file in files:
        if file.endswith('.csv') and file.startswith("5"):
            name = os.path.splitext(file)[0]
            df = pd.read_csv(file,thousands=",")
            df = df[0:75]
            df["Date"] = pd.to_datetime(df["Date"])
            df.sort_values(by="Date",inplace=True)
            
            try :
                start = df["Close"].iloc[0]
            except Exception as e:
                start = df["Close Price"].iloc[0]
            
            try :
                end = df["Close"].iloc[-1]
            except Exception as e:
                end = df["Close Price"].iloc[-1]
            gain = (end/start) - 1
            data[name] = gain

In [16]:
df = pd.DataFrame(data.items(),columns=["security","gain"])
df.sort_values(by="gain",inplace=True,ascending=False)
df.head(10)

    security      gain
252   523558  5.232323
279   524661  3.269231
293   526638  2.924000
226   521210  2.492647
104   504340  2.369565
229   521222  2.053571
69    500306  1.916185
310   531676  1.600000
110   508664  1.589577
146   511618  1.538462

# identify the top 10 gainers (%) across groups over the 1 month period.

In [17]:
data = {}
for root,dirs,files in os.walk(os.curdir):
    for file in files:
        if file.endswith('.csv') and file.startswith("5"):
            name = os.path.splitext(file)[0]
            df = pd.read_csv(file,thousands=",")
            df = df[0:30]
            df["Date"] = pd.to_datetime(df["Date"])
            df.sort_values(by="Date",inplace=True)
            
            try :
                start = df["Close"].iloc[0]
            except Exception as e:
                start = df["Close Price"].iloc[0]
            
            try :
                end = df["Close"].iloc[-1]
            except Exception as e:
                end = df["Close Price"].iloc[-1]
            gain = (end/start) - 1
            data[name] = gain

In [18]:
df = pd.DataFrame(data.items(),columns=["security","gain"])
df.sort_values(by="gain",inplace=True,ascending=False)
df.head(10)

    security      gain
293   526638  1.687671
116   511431  1.512241
6     500013  1.491991
69    500306  1.466993
322   532928  1.043435
186   517498  0.970655
216   521151  0.906383
64    500296  0.905983
7     500014  0.902174
140   511593  0.843243

In [20]:
icici_bank = "ICICI_Bank"
df_icici_bank = pd.read_csv(icici_bank + ".csv",thousands=",")

stock_corr = pd.DataFrame()
for root,dirs,files in os.walk(os.curdir):
    for file in files:
        if file.endswith('.csv') and file.startswith("5"):
            name = os.path.splitext(file)[0]
            if name == icici_bank:
                continue
            df = pd.read_csv(file,thousands=",")
            cor = df_icici_bank["Total Turnover (Rs.)"].corr(df["Total Turnover (Rs.)"])
            try:
                stock_corr = stock_corr.append({'security' : name, 'correlation' : cor, 'name' : security_names[int(name)]},  
                ignore_index = True)
            except Exception as e:
                pass
            

stock_corr = stock_corr.sort_values(by="correlation",ascending=False)
stock_corr.head()

C:\Users\cgm\anaconda3\lib\site-packages\numpy\lib\function_base.py:2634: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
C:\Users\cgm\anaconda3\lib\site-packages\numpy\lib\function_base.py:2493: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)

     correlation                                           name security
91      1.000000                SUNRISE INDUSTRIAL TRADERS LTD.   501110
151     0.637759                     Evergreen Textiles Limited   514060
300     0.429237                         RSC INTERNATIONAL LTD.   530179
219     0.288419      SRI RAMAKRISHNA MILLS (COIMBATORE) LTD.-$   521178
178     0.278666  NARMADA MACPLAST DRIP IRRIGATION SYSTEMS LTD.   517431

# Draw a correlation matrix of any 30 stocks on the Sensex. This is a matrix with both axes holding the stock names. The colour of each cell is the correlation between that pair of stocks: blue for -1 and green for 1.

In [21]:
dfs = {}
stock_names = set()
def read_dfs():
    for root,dirs,files in os.walk(os.curdir):
        for file in files:
            if len(stock_names) == 30:
                return
            if file.endswith('.csv') and file.startswith("5"):
                name = os.path.splitext(file)[0]
                df = pd.read_csv(file,thousands=",")
                dfs[name] = df
                stock_names.add(name)
read_dfs()

In [22]:
samp = pd.DataFrame(columns=stock_names,index=stock_names)
for n1,n2 in combinations(stock_names,2):
    df1 = dfs[n1]
    df2 = dfs[n2]
    c1 = df1["Total Turnover (Rs.)"].corr(df2["Total Turnover (Rs.)"])
    c2 = df2["Total Turnover (Rs.)"].corr(df1["Total Turnover (Rs.)"])
    samp.loc[n1,n2] = c1
    samp.loc[n2,n1] = c2
    samp.loc[n1,n1] = 1
    samp.loc[n2,n2] = 1
samp = samp.astype({name:"float" for name in stock_names})

In [23]:
samp.style.background_gradient(cmap="brg")

# Draw a sparkline showing the data 23,80,92,62,98,7,9,56,19,68.

In [24]:
import base64
import io


def spark_line(data, figsize=(4, 0.25), **kwags):
    data = list(data)

    fig, ax = plt.subplots(1, 1, figsize=figsize, **kwags)
    ax.plot(data)
    for k,v in ax.spines.items():
        v.set_visible(False)
    ax.set_xticks([])
    ax.set_yticks([])

    plt.plot(len(data) - 1, data[len(data) - 1], 'r.')

    ax.fill_between(range(len(data)), data, len(data)*[min(data)], alpha=0.1)

    img = io.BytesIO()
    plt.savefig(img, transparent=True, bbox_inches='tight')
    img.seek(0)
    plt.close()

    return base64.b64encode(img.read()).decode("UTF-8")

In [27]:
values = [23,80,92,62,98,7,9,56,19,68]


with open("sparkline.html", "a") as file:
        file.write('<div><h1>Sparkline to the given values</h1></div>')
        file.write('<br>')
        file.write('<br>')
        file.write('<div><img src="data:image/png;base64,{}"/></div>'.format(spark_line(values)))
        file.write('<div></div>')

# For each stock, draw a sparkline showing last month's closing price trend

In [28]:
closing_price_values = list()
for file in os.listdir():
    if file.endswith('.csv') and file.startswith("5"):
        filename = os.path.splitext(file)[0]
        if not filename.isdecimal() :
            continue
        df = pd.read_csv(file,thousands=",")
        try:
            closing_price_values.append(df["Close"][0:30].values)
        except Exception as e:
            closing_price_values.append(df["Close Price"][0:30].values)

with open("bse_closing_price.html", "a") as file:
    file.write('<div><h1>Sparkline to the Closing Price values</h1></div>')
    file.write('<br>')
    file.write('<br>')
    for value in closing_price_values:
        file.write('<div><img src="data:image/png;base64,{}"/></div>'.format(spark_line(value)))
        file.write('<div></div>')

# Convert these files into PDF without using a browser

In [30]:
client = pdfcrowd.HtmlToPdfClient('demo', 'ce544b6ea52a5621fb9d55f8b542d14d')
client.convertFileToFile('bse_closing_price.html', 'bse_closing_price.pdf')